// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dxXjqVzWaQjT-WItPworq3VLvlmBj4w',
    appId: '1:243354411490:web:7d7b2d3cf48ffd93e5d9bb',
    messagingSenderId: '243354411490',
    projectId: 'fir-crud19924',
    authDomain: 'fir-crud19924.firebaseapp.com',
    storageBucket: 'fir-crud19924.appspot.com',
    measurementId: 'G-G27ZGV7FEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yqUcoHV64xdvK3sbv9HRZq0UVsijaFg',
    appId: '1:243354411490:android:23bcbb8d388a243ee5d9bb',
    messagingSenderId: '243354411490',
    projectId: 'fir-crud19924',
    storageBucket: 'fir-crud19924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKf9C71Mg2RAk9_4OHX-DX9yFJxBuFvJU',
    appId: '1:243354411490:ios:bfdf304ec73c09fce5d9bb',
    messagingSenderId: '243354411490',
    projectId: 'fir-crud19924',
    storageBucket: 'fir-crud19924.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKf9C71Mg2RAk9_4OHX-DX9yFJxBuFvJU',
    appId: '1:243354411490:ios:bfdf304ec73c09fce5d9bb',
    messagingSenderId: '243354411490',
    projectId: 'fir-crud19924',
    storageBucket: 'fir-crud19924.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1dxXjqVzWaQjT-WItPworq3VLvlmBj4w',
    appId: '1:243354411490:web:7f7087da9d2c09fce5d9bb',
    messagingSenderId: '243354411490',
    projectId: 'fir-crud19924',
    authDomain: 'fir-crud19924.firebaseapp.com',
    storageBucket: 'fir-crud19924.appspot.com',
    measurementId: 'G-V2HMQZFX8F',
  );
}
